# Keyboard/input specific to ossoarchy
# Physical keyboard: US ANSI
# Daily workflow: Portuguese typing, with toggle to US when needed.

input {
  kb_layout = pt,us
  kb_variant = ,
  kb_options = grp:shifts_toggle,ctrl:nocaps
  kb_model = pc104

  repeat_rate = 40
  repeat_delay = 600
  numlock_by_default = true

  touchpad {
    scroll_factor = 0.4
  }
}

windowrule = match:class (Alacritty|kitty), scroll_touchpad 1.5
windowrule = match:class com.mitchellh.ghostty, scroll_touchpad 0.2
